[tool.poetry]
name = "python-qr"
version = "1.0.0"
description = ""
authors = ["RLAlpha49 <75044176+RLAlpha49@users.noreply.github.com>"]
readme = "README.md"
license = "MIT"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9.8"
streamlit = "^1.36.0"
qrcode = "^7.4.2"

[tool.poetry.dev-dependencies]
types-requests = "*"
isort = "^5.13.2"
black = "^24.4.2"
pylint = "^3.2.5"
mypy = "^1.11.0"
flake8 = "^7.1.0"

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.flake8]
max-line-length = 120

[tool.pylint]
max-line-length = 120

[tool.mypy]
disable_error_code = "import-untyped"